# Generated by Django 4.1.2 on 2022-11-13 17:52

"""
0001_initial.py

Modulo generado por Django para mostrar las operaciones, campos y opciones que se realizaron durante la migración.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Se encarga de clasificar los contenidos que estan vinculados a la migración generada.

    Args:
        migrations (Migration): Sirve para propagar los cambios que realiza en sus modelos (agregar un campo, eliminar un modelo, etc.) 
        en el esquema de la base de datos.

    Parameters:
        dependencies (list): Lista de tuplas de (app_path, migration_name)
        operations (list): Lista de instancias de operación.

    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('idFecha', models.DateTimeField(auto_now_add=True)),
                ('idAsignatura', models.CharField(max_length=255)),
                ('idCarrera', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'db_table': 'mesas',
                'ordering': ('idAsignatura',),
            },
        ),
    ]
