# Generated by Django 4.1.2 on 2022-11-13 17:59

"""
0002_alter_mesas_hora_alter_mesas_idFecha.py

Modulo generado por Django para mostrar las operaciones, campos y opciones que se realizaron durante la migración.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Se encarga de clasificar los contenidos que estan vinculados a la migración generada.

    Args:
        migrations (Migration): Sirve para propagar los cambios que realiza en sus modelos (agregar un campo, eliminar un modelo, etc.) 
        en el esquema de la base de datos.

    Parameters:
        dependencies (list): Lista de tuplas de (app_path, migration_name)
        operations (list): Lista de instancias de operación.

    """
    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='hora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesas',
            name='idFecha',
            field=models.IntegerField(),
        ),
    ]
