# Generated by Django 4.1.2 on 2022-11-13 20:13

"""
0003_alter_mesas_options_remove_mesas_hora_and_more.py

Modulo generado por Django para mostrar las operaciones, campos y opciones que se realizaron durante la migración.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Se encarga de clasificar los contenidos que estan vinculados a la migración generada.

    Args:
        migrations (Migration): Sirve para propagar los cambios que realiza en sus modelos (agregar un campo, eliminar un modelo, etc.) 
        en el esquema de la base de datos.

    Parameters:
        dependencies (list): Lista de tuplas de (app_path, migration_name)
        operations (list): Lista de instancias de operación.

    """
    dependencies = [
        ('mesas', '0002_alter_mesas_hora_alter_mesas_idfecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesas',
            options={'ordering': ('idFecha',), 'verbose_name': 'mesa', 'verbose_name_plural': 'mesas'},
        ),
        migrations.RemoveField(
            model_name='mesas',
            name='hora',
        ),
        migrations.AlterField(
            model_name='mesas',
            name='idFecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
